HDMI CEC Steuerung mit CEC lib oder cec-utils
stg93/blaulichtsms_einsatzmonitor_tv_controller pull request #13
Opened 2019-02-14 08:25 UTC by r00tat

Ich habe selbst auch etwas ähnliches gebaut um den Monitor für eine BlaulichtSMS Anzeige zu steuern, allerdings war dies nicht so weit fort geschritten und dadurch auch nicht Open Source. 

Da dieses Projekt jedoch einige Vorteile bietet, habe ich jetzt unsere Monitore auch umgestellt. Leider habe ich festgestellt, dass das ein und ausschalten der Monitore nicht sauber funktioniert.

Folgende 2 Ursachen habe ich eruieren können:

1. Die python cec lib funktioniert nicht verlässlich
2. Der Algorithmus für das ausschalten funktioniert nicht, wenn in der Zwischenzeit ein weiter Alarm herein kommt

ad 1:

Ich habe direkt versucht den Monitor mit der python cec lib ein und auszuschalten, dies hat aber nur in manche der Fälle funktioniert. Manchmal hat die cec lib dann zurück geliefert der Monitor ist ein, er war aber aus. Einschalten hat auch oft einfach gar nicht funktioniert.
In meinem bisherigen Python Program habe ich hier einfach `cec-client` über `subprocess` aufgerufen, ist nicht ganz schön, aber verlässlich. Ich habe dies jetzt als Option über einen cec_helper implementiert. In der Config kann man mit `cec_mode = 2` auf cec-utils wechseln, default ist weiterhin die python cec lib.

ad 2:

Das Ausschalten des Monitors erfolgte immer einfach Zeitverzögert. Hierbei wurde nicht geprüft, ob vielleicht in der Zwischenzeit schon ein weiterer Alarm herein gekommen ist. Dadurch kann es sein, dass der Monitor sich ausschaltet, obwohl ein Alarm aktiv ist. Genau so wird nicht geprüft, ob sich vielleicht der Status des Monitors geändert hat (jemand hat mit der Fernbedienung herum gedrückt). 
Um dies zu lösen, wird bei der Berechnung ob ein Alarm aktiv ist, auch die `hdmi_cec_device_on_time` an den BlaulichtSMS Controller übergeben. Somit wird nicht nur überprüft, ob ein neuer Alarm dazu gekommen ist, sondern ob einer der Alarme im aktuellen Zeitraum liegt. 

Ich freue mich über Feedback zum Pull Request.

2019-02-14 19:13 UTC, stg93 requested changes

2019-02-14 19:13 UTC, stg93 commented on blaulichtsmscontroller.py
> +            return response_json.get("alarms", []) + response_json.get("infos", [])
Ob der Monitor *infos* berücksichtigt sollte über ein Flag im config File konfigurierbar sein, da es Fälle gibt wo die *infos* nicht interessant sind.

2019-02-14 19:13 UTC, stg93 commented on cec_helper.py
> +class CecFactory(object):
Ich habe keine Stelle gefunden wo diese Factory verwendet wird.

2019-02-14 19:13 UTC, stg93 commented on cec_helper.py
> +class CecHelper(object):
Um hier ein formaleres Interface zu bekommen wäre es glaube ich besser wenn CecHelper von **abs.ABS** erbt. Die Methoden können dann mit **@abstractmethod** annotiert werden.

2019-02-14 19:13 UTC, stg93 commented on cec_helper.py
> +            self.logger.warn("failed to get monitor status %s %s", err.returncode, err.output)
*logger.warn* ist deprecated, verwende stattdessen *logger.warning*.

2019-02-14 19:13 UTC, stg93 commented on cec_helper.py
> +            self.logger.warn("failed to set monitor status %s %s", err.returncode, err.output)
*logger.warn* ist deprecated, verwende stattdessen *logger.warning*.

2019-02-14 19:13 UTC, stg93 commented on hdmiceccontroller.py
> +            self.logger.warn("deprecated: duration")
*logger.warn* ist deprecated, verwende stattdessen *logger.warning*.

2019-02-14 19:13 UTC, stg93 commented on blaulichtsmscontroller.py
> +    def is_alarm(self, time_interval):
Der neue Parameter muss auch in *alarmmonitortest.py* übernommen werden.

2019-02-22 19:40 UTC, r00tat commented on cec_helper.py
> +class CecFactory(object):
Die Idee war zuerst die Factory zu nutzen, aber habe ich dann nicht verwendet.

2019-02-22 20:05 UTC, r00tat commented
@stg93 Änderungen und Vorschläge sind übernommen!

2019-02-24 20:22 UTC, stg93 approved these changes

2019-02-24 20:26 UTC, merged